### PR TITLE
OFAT & Sobol

### PR DESCRIPTION
**Pull request by jerbaroo**
# Happiness OFAT

OFAT default params are [1, 1, 1, 1, 120] for betas and class size respectively.

screen shot 2018-01-31 at 00 26 01

### CODE REVIEW

**Comment by barischrooneyj** [comment]
Hey @al165 . For SA I'm using each of the three measures lbp, clusters and entropy
I'm taking the sum of the lists they return since the analyze.sobol method wants
a single numerical value.

Any idea how to adapt lbp for this purpose since its sum is always the same?

## Preliminary results.

***

Results for a run taking 100 samples, (1200 model runs, see
(salib)[http://salib.readthedocs.io/en/latest/basics.html#generate-samples])
~5min:

**Shows number of people to be the only significant component., albeit with low confidence.**

Sensitivity using clusters:

{'S1': array([ 1.01514126,  0.00878828, -0.00336659, -0.00373164,  0.01165461]),
 'S1_conf': array([0.26324281, 0.02655605, 0.02483503, 0.02795545, 0.02993607]),
 'S2': array([[        nan, -0.00075714,  0.02065922,  0.01238472,  0.02228168],
       [        nan,         nan, -0.00799058, -0.00912629, -0.00636812],
       [        nan,         nan,         nan, -0.0062194 , -0.00232551],
       [        nan,         nan,         nan,         nan, -0.00183878],
       [        nan,         nan,         nan,         nan,         nan]]),
 'S2_conf': array([[       nan, 0.29077998, 0.28593336, 0.28937813, 0.29309443],
       [       nan,        nan, 0.03541967, 0.03539353, 0.03531014],
       [       nan,        nan,        nan, 0.0379265 , 0.03839949],
       [       nan,        nan,        nan,        nan, 0.03297138],
       [       nan,        nan,        nan,        nan,        nan]]),
 'ST': array([1.02944588, 0.01087043, 0.00884236, 0.00811226, 0.01395309]),
 'ST_conf': array([0.21362023, 0.00479832, 0.00439999, 0.00310888, 0.00666021])}

Sensitivity using entropy:

{'S1': array([ 0.91177126, -0.00840892, -0.02712254,  0.04232077, -0.01743588]),
 'S1_conf': array([0.331923  , 0.09072587, 0.0744653 , 0.08920348, 0.08121346]),
 'S2': array([[        nan,  0.01328563,  0.00322153, -0.0160791 ,  0.01996628],
       [        nan,         nan,  0.00673681, -0.02548828, -0.02732594],
       [        nan,         nan,         nan,  0.04455674,  0.04168714],
       [        nan,         nan,         nan,         nan, -0.0249772 ],
       [        nan,         nan,         nan,         nan,         nan]]),
 'S2_conf': array([[       nan, 0.5907394 , 0.58061414, 0.59901263, 0.58253696],
       [       nan,        nan, 0.16662723, 0.18115604, 0.17539444],
       [       nan,        nan,        nan, 0.16449323, 0.15280085],
       [       nan,        nan,        nan,        nan, 0.14475564],
       [       nan,        nan,        nan,        nan,        nan]]),
 'ST': array([1.07390557, 0.12072105, 0.12086568, 0.12683954, 0.14566376]),
 'ST_conf': array([0.21031921, 0.05328875, 0.05071149, 0.05174328, 0.06425633])}


***

Run with **class size fixed to 100**, same number of samples as above.

Sensitivity using clusters:

{'S1': array([-0.04115756,  0.06873884, -0.14426581,  0.25008932]),
 'S1_conf': array([0.24382107, 0.2409741 , 0.23522931, 0.28831851]),
 'S2': array([[        nan, -0.05155413,  0.05562701,  0.01989996],
       [        nan,         nan,  0.14290818, -0.32154341],
       [        nan,         nan,         nan,  0.01718471],
       [        nan,         nan,         nan,         nan]]),
 'S2_conf': array([[       nan, 0.3313003 , 0.35674894, 0.36148012],
       [       nan,        nan, 0.31103745, 0.37115665],
       [       nan,        nan,        nan, 0.29370737],
       [       nan,        nan,        nan,        nan]]),
 'ST': array([0.64308682, 0.75026795, 0.82172204, 0.92890318]),
 'ST_conf': array([0.18334235, 0.16042422, 0.20744433, 0.24608957])}

Sensitivity using entropy:

{'S1': array([ 0.0167237 ,  0.06571555, -0.26519297,  0.22113358]),
 'S1_conf': array([0.21467408, 0.22659098, 0.18561103, 0.38091993]),
 'S2': array([[        nan, -0.04352456,  0.09896564, -0.03454024],
       [        nan,         nan,  0.20433027, -0.4896529 ],
       [        nan,         nan,         nan,  0.19297557],
       [        nan,         nan,         nan,         nan]]),
 'S2_conf': array([[       nan, 0.36476898, 0.31289771, 0.39330974],
       [       nan,        nan, 0.28949213, 0.45012321],
       [       nan,        nan,        nan, 0.36059499],
       [       nan,        nan,        nan,        nan]]),
 'ST': array([0.91600199, 1.06146072, 0.97706496, 1.38351699]),
 'ST_conf': array([0.41169402, 0.25369912, 0.25253584, 0.64122482])}

Sensitivity using lbp:

**Comment by barischrooneyj** [comment]
## Preliminary Sobol results.

***

Results for a run taking 100 samples, (1200 model runs, see [salib](http://salib.readthedocs.io/en/latest/basics.html#generate-samples)) ~5min:

**Shows number of people to be the only significant component., albeit with low confidence.**

Sensitivity using clusters:

{'S1': array([ 1.01514126,  0.00878828, -0.00336659, -0.00373164,  0.01165461]),
 'S1_conf': array([0.26324281, 0.02655605, 0.02483503, 0.02795545, 0.02993607]),
 'S2': array([[        nan, -0.00075714,  0.02065922,  0.01238472,  0.02228168],
       [        nan,         nan, -0.00799058, -0.00912629, -0.00636812],
       [        nan,         nan,         nan, -0.0062194 , -0.00232551],
       [        nan,         nan,         nan,         nan, -0.00183878],
       [        nan,         nan,         nan,         nan,         nan]]),
 'S2_conf': array([[       nan, 0.29077998, 0.28593336, 0.28937813, 0.29309443],
       [       nan,        nan, 0.03541967, 0.03539353, 0.03531014],
       [       nan,        nan,        nan, 0.0379265 , 0.03839949],
       [       nan,        nan,        nan,        nan, 0.03297138],
       [       nan,        nan,        nan,        nan,        nan]]),
 'ST': array([1.02944588, 0.01087043, 0.00884236, 0.00811226, 0.01395309]),
 'ST_conf': array([0.21362023, 0.00479832, 0.00439999, 0.00310888, 0.00666021])}

Sensitivity using entropy:

{'S1': array([ 0.91177126, -0.00840892, -0.02712254,  0.04232077, -0.01743588]),
 'S1_conf': array([0.331923  , 0.09072587, 0.0744653 , 0.08920348, 0.08121346]),
 'S2': array([[        nan,  0.01328563,  0.00322153, -0.0160791 ,  0.01996628],
       [        nan,         nan,  0.00673681, -0.02548828, -0.02732594],
       [        nan,         nan,         nan,  0.04455674,  0.04168714],
       [        nan,         nan,         nan,         nan, -0.0249772 ],
       [        nan,         nan,         nan,         nan,         nan]]),
 'S2_conf': array([[       nan, 0.5907394 , 0.58061414, 0.59901263, 0.58253696],
       [       nan,        nan, 0.16662723, 0.18115604, 0.17539444],
       [       nan,        nan,        nan, 0.16449323, 0.15280085],
       [       nan,        nan,        nan,        nan, 0.14475564],
       [       nan,        nan,        nan,        nan,        nan]]),
 'ST': array([1.07390557, 0.12072105, 0.12086568, 0.12683954, 0.14566376]),
 'ST_conf': array([0.21031921, 0.05328875, 0.05071149, 0.05174328, 0.06425633])}


***

Run with **class size fixed to 100**, same number of samples as above.

Sensitivity using clusters:

{'S1': array([-0.04115756,  0.06873884, -0.14426581,  0.25008932]),
 'S1_conf': array([0.24382107, 0.2409741 , 0.23522931, 0.28831851]),
 'S2': array([[        nan, -0.05155413,  0.05562701,  0.01989996],
       [        nan,         nan,  0.14290818, -0.32154341],
       [        nan,         nan,         nan,  0.01718471],
       [        nan,         nan,         nan,         nan]]),
 'S2_conf': array([[       nan, 0.3313003 , 0.35674894, 0.36148012],
       [       nan,        nan, 0.31103745, 0.37115665],
       [       nan,        nan,        nan, 0.29370737],
       [       nan,        nan,        nan,        nan]]),
 'ST': array([0.64308682, 0.75026795, 0.82172204, 0.92890318]),
 'ST_conf': array([0.18334235, 0.16042422, 0.20744433, 0.24608957])}

Sensitivity using entropy:

{'S1': array([ 0.0167237 ,  0.06571555, -0.26519297,  0.22113358]),
 'S1_conf': array([0.21467408, 0.22659098, 0.18561103, 0.38091993]),
 'S2': array([[        nan, -0.04352456,  0.09896564, -0.03454024],
       [        nan,         nan,  0.20433027, -0.4896529 ],
       [        nan,         nan,         nan,  0.19297557],
       [        nan,         nan,         nan,         nan]]),
 'S2_conf': array([[       nan, 0.36476898, 0.31289771, 0.39330974],
       [       nan,        nan, 0.28949213, 0.45012321],
       [       nan,        nan,        nan, 0.36059499],
       [       nan,        nan,        nan,        nan]]),
 'ST': array([0.91600199, 1.06146072, 0.97706496, 1.38351699]),
 'ST_conf': array([0.41169402, 0.25369912, 0.25253584, 0.64122482])}

**Comment by barischrooneyj** [comment]
screen shot 2018-01-30 at 16 29 37

**Comment by barischrooneyj** [comment]
# Another cluster method OFAT
screen shot 2018-01-30 at 17 55 06

# Happiness OFAT
@FionaLippert @al165 
x-axis is 0-1 for each beta value.
y-axis values are the sum of happiness.

screen shot 2018-01-30 at 18 29 35

**Comment by barischrooneyj** [comment]
Will run a Sobol using Happiness, upload later tonight as busy for a while.

**Comment by jerbaroo** [comment]
# Sobol using happiness measure, 12000 Saltelli samples.

{'S1': array([0.05364624, 0.00408565, 0.16032171, 0.058425  , 0.60512588]),
 'S1_conf': array([0.02445543, 0.01565264, 0.04533397, 0.02803779, 0.07241162]),
 'S2': array([[        nan, -0.01327164, -0.01036628, -0.00540556,  0.00590353],
       [        nan,         nan,  0.00417216, -0.00352754,  0.00233764],
       [        nan,         nan,         nan, -0.00926876,  0.08682297],
       [        nan,         nan,         nan,         nan,  0.00719558],
       [        nan,         nan,         nan,         nan,         nan]]),
 'S2_conf': array([[       nan, 0.03781868, 0.03693503, 0.03936874, 0.0474542 ],
       [       nan,        nan, 0.02458051, 0.02593276, 0.02691976],
       [       nan,        nan,        nan, 0.06786221, 0.07059963],
       [       nan,        nan,        nan,        nan, 0.04818242],
       [       nan,        nan,        nan,        nan,        nan]]),
 'ST': array([0.0807699 , 0.02974095, 0.26540673, 0.08993911, 0.74202895]),
 'ST_conf': array([0.01456117, 0.00590054, 0.04072848, 0.01683967, 0.08055415])}

**Pull request merged**
